name: 'TheRevio Code Review'
description: 'AI-powered code review for your pull requests'
author: 'TheRevio'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  backend_url:
    description: 'TheRevio backend WebSocket URL'
    required: true
  api_key:
    description: 'TheRevio API key (create in UI)'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  fail_safe:
    description: 'Exit with success code even if review fails'
    required: false
    default: 'true'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run TheRevio agent
      shell: bash
      run: |
        docker run --rm \
          -e BACKEND_URL="${{ inputs.backend_url }}" \
          -e THEREVIO_API_KEY="${{ inputs.api_key }}" \
          -e GITHUB_TOKEN="${{ inputs.github_token }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SHA="${{ github.sha }}" \
          -e GITHUB_REF="${{ github.ref }}" \
          -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
          -e GITHUB_API_URL="${{ github.api_url }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}" \
          -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
          -e GITHUB_BASE_REF="${{ github.base_ref }}" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_ACTIONS="true" \
          -e FAIL_SAFE="${{ inputs.fail_safe }}" \
          -e DEBUG="${{ inputs.debug }}" \
          -e REPO_PATH="/workspace" \
          -v "${{ github.workspace }}:/workspace" \
          ilyaplot/revio-agent-github:latest
